### ISSUE TITLE
TypeScript - Stricter type checking

### ISSUE THREAD

**Issue by PieterWillemen** [PeytonRG/BootstrapToaster#14]
Hi,

I tried to use this library in a typescript project using webpack.
Unfortunately, the TypeScript (v4.4.4) compiler is throwing roughly 20 type check errors.
Most of them are null/undefined related, e.g. Cannot assign type undefined to type number.

Could you perhaps upgrade your version of TypeScript and fix these?

**Comment by PeytonRG** [comment]
I added ESLint to the v5-dev branch and fixed the errors it identified with TypeScript 4.5.2. Checkout the latest commit and see if that fixes your issues.

**Comment by PeytonRG** [comment]
Closed due to lack of response
