### ISSUE TITLE
ESM Module

### ISSUE THREAD

**Issue by philipp-winterle** [PeytonRG/BootstrapToaster#15]
**Is your feature request related to a problem? Please describe.**
For the usage of tree shaking and bundles size and the usage in modules anyway it is recommended to bring Bootstrap Toaster as a esm module. 

**Describe the solution you'd like**
Convert to esm module

**Describe alternatives you've considered**
Bring both

**Comment by PeytonRG** [comment]
I know it's been literally forever, and you've probably moved on but I'm finally close to getting this bundled as both UMD and ESM modules for 5.2.0.

**Comment by philipp-winterle** [comment]
Nice job. But as you said I already moved on. I needed a fast working solution so I created my own implementation. 
Thank you for coming back. :)
