### ISSUE TITLE
Support for ES6 Modules

### ISSUE THREAD

**Issue by mamiksik** [PeytonRG/BootstrapToaster#6]
Hi, would it be possible to add support for ES6 modules? i.e export Toast class and constants + import the boostrap Toaster using import { Toast } from "bootstrap"?

Currently, I cannot use this lib with webpack and babel.

**Comment by PeytonRG** [comment]
I will look into supporting this!

**Comment by PeytonRG** [comment]
I wouldn't call it finished, but you can try out the new 5.1.0-beta1 release on a test page or something and see if that works for you. I've never used webpack in a personal project so I haven't tested that myself, but I have tested that es6 import/export seems to be working. The v5-dev branch's docs/index.js is currently using it
